# Generated by Django 6.0.8 on 2026-09-03 08:43

import apps.users.managers
import django.db.models.deletion
import utils.phone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('first_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Nom')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, validators=[utils.phone.validate_phone_number], verbose_name='Téléphone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Membre du personnel')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('is_proprietaire', models.BooleanField(default=False, verbose_name='Propriétaire')),
                ('is_responsable_pharmacie', models.BooleanField(default=False, verbose_name='Responsable pharmacie')),
                ('is_vendeur_pharmacie', models.BooleanField(default=False, verbose_name='Vendeur pharmacie')),
                ('is_caissier', models.BooleanField(default=False, verbose_name='Caissier')),
                ('is_agent_accueil', models.BooleanField(default=False, verbose_name="Agent d'accueil")),
                ('is_personnel_medical', models.BooleanField(default=False, verbose_name='Personnel médical')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('specialite', models.CharField(blank=True, default='', max_length=100, verbose_name='Spécialité')),
                ('numero_ordre', models.CharField(blank=True, default='', max_length=50, verbose_name="Numéro d'ordre professionnel")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil médical',
                'verbose_name_plural': 'Profils médicaux',
                'db_table': 'medical_profiles',
                'constraints': [models.UniqueConstraint(condition=models.Q(('numero_ordre', ''), _negated=True), fields=('numero_ordre',), name='unique_numero_ordre_non_empty')],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('code_hash', models.CharField(max_length=128, verbose_name='Hash du code OTP')),
                ('purpose', models.CharField(choices=[('registration', 'Inscription'), ('password_reset', 'Réinitialisation mot de passe')], max_length=30, verbose_name='Objectif')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('is_used', models.BooleanField(default=False, verbose_name='Déjà utilisé')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'utilisation")),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Nombre de tentatives')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Code OTP',
                'verbose_name_plural': 'Codes OTP',
                'db_table': 'otps',
                'indexes': [models.Index(fields=['user', 'purpose', 'is_used', '-created_at'], name='otps_lookup_idx')],
            },
        ),
    ]
