# Generated by Django 6.0.8 on 2026-09-03 11:13

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[utils.validators.validate_image_file_size], verbose_name='Photo de profil'),
        ),
    ]
