# Generated by Django 6.0.8 on 2026-09-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Inscription'), ('password_reset', 'Réinitialisation mot de passe'), ('two_factor', 'Authentification à deux facteurs')], max_length=30, verbose_name='Objectif'),
        ),
    ]
