# Generated by Django 6.0.8 on 2026-09-16 22:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('is_deleted', models.BooleanField(default=False, help_text="Indique si l'enregistrement a été supprimé logiquement.", verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date de suppression')),
                ('patient_number', models.CharField(db_index=True, help_text='Numéro unique généré automatiquement au format PAT-YYYY-XXXX.', max_length=32, unique=True, verbose_name='Matricule / Identifiant patient')),
                ('first_name', models.CharField(max_length=150, verbose_name='Prénom(s)')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nom de famille')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], default='O', max_length=1, verbose_name='Sexe / Genre')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('UNKNOWN', 'Non déterminé')], default='UNKNOWN', max_length=10, verbose_name='Groupe sanguin')),
                ('phone_number', models.CharField(db_index=True, max_length=20, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse email')),
                ('address', models.TextField(blank=True, default='', verbose_name='Adresse de résidence')),
                ('profession', models.CharField(blank=True, default='', max_length=150, verbose_name='Profession')),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=200, verbose_name="Nom du contact d'urgence")),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=20, verbose_name="Téléphone du contact d'urgence")),
                ('emergency_contact_relation', models.CharField(blank=True, default='', max_length=100, verbose_name='Lien de parenté')),
                ('allergies', models.TextField(blank=True, default='', help_text='Mentionner toutes les allergies médicamenteuses, alimentaires ou respiratoires.', verbose_name='Allergies connues')),
                ('chronic_diseases', models.TextField(blank=True, default='', help_text='Ex: Diabète type 2, HTA, Asthme, Drépanocytose, etc.', verbose_name='Affections chroniques / Antécédents majeurs')),
                ('is_active', models.BooleanField(default=True, verbose_name='Dossier actif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patients',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('is_deleted', models.BooleanField(default=False, help_text="Indique si l'enregistrement a été supprimé logiquement.", verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date de suppression')),
                ('scheduled_at', models.DateTimeField(db_index=True, verbose_name='Date et heure du rendez-vous')),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Durée estimée (minutes)')),
                ('reason', models.CharField(max_length=255, verbose_name='Motif de consultation')),
                ('status', models.CharField(choices=[('scheduled', 'Programmé'), ('waiting', 'En attente'), ('in_consultation', 'En consultation'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('missed', 'Non honoré / Absent')], db_index=True, default='scheduled', max_length=20, verbose_name='Statut du rendez-vous')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes ou observations')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Médecin / Praticien')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'db_table': 'appointments',
                'ordering': ['scheduled_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_deleted', '-created_at'], name='patient_active_created_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name', 'first_name'], name='patient_name_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone_number'], name='patient_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['patient_number'], name='patient_num_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['is_deleted', '-created_at'], name='appointment_active_created_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'scheduled_at'], name='rdv_doctor_date_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'scheduled_at'], name='rdv_status_date_idx'),
        ),
    ]
