# Generated by Django 6.0.8 on 2026-09-16 23:29

import utils.phone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[utils.phone.validate_phone_number], verbose_name="Téléphone du contact d'urgence"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20, validators=[utils.phone.validate_phone_number], verbose_name='Numéro de téléphone'),
        ),
    ]
