# Generated by Django 6.0.8 on 2026-09-17 05:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_emergency_contact_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Nom de la substance')),
                ('category', models.CharField(choices=[('medication', 'Médicament / Molécule active'), ('food', 'Alimentaire'), ('environment', 'Environnemental / Aéro-allergène'), ('biological', 'Biologique / Latex / Venin'), ('other', 'Autre substance')], db_index=True, default='medication', max_length=30, verbose_name='Catégorie')),
                ('atc_code', models.CharField(blank=True, db_index=True, default='', help_text="Code de classification anatomique, thérapeutique et chimique de l'OMS (ex: J01C).", max_length=20, verbose_name='Code ATC')),
                ('cross_reactivity_group', models.CharField(blank=True, db_index=True, default='', help_text='Ex: Bêta-lactamines, Sulfamides, AINS.', max_length=100, verbose_name='Groupe de réactivité croisée')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description / Précisions pharmacologiques')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Allergène',
                'verbose_name_plural': 'Allergènes',
                'db_table': 'allergens',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('criticality', models.CharField(choices=[('low', 'Faible (réaction mineure)'), ('moderate', 'Modérée'), ('high', 'Élevée (Risque vital / Anaphylaxie)'), ('unable_to_assess', 'Indéterminée')], db_index=True, default='high', max_length=25, verbose_name='Niveau de criticité')),
                ('verification_status', models.CharField(choices=[('suspected', 'Suspectée / Déclarée par le patient'), ('confirmed', 'Confirmée par bilan / Praticien'), ('refuted', 'Réfutée / Erronée')], default='confirmed', max_length=25, verbose_name='Statut de vérification')),
                ('reaction', models.CharField(blank=True, default='', help_text='Ex: Œdème de Quincke, Choc anaphylactique, Urticaire, Bronchospasme...', max_length=255, verbose_name='Manifestation clinique / Réaction')),
                ('diagnosed_date', models.DateField(blank=True, null=True, verbose_name='Date du diagnostic')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observations médicales complémentaires')),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_allergies', to='patients.allergen', verbose_name='Allergène / Substance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_allergies', to='patients.patient', verbose_name='Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Allergie patient',
                'verbose_name_plural': 'Allergies patients',
                'db_table': 'patient_allergies',
                'ordering': ['-criticality', 'allergen__name'],
            },
        ),
        migrations.AddIndex(
            model_name='allergen',
            index=models.Index(fields=['name'], name='allergen_name_idx'),
        ),
        migrations.AddIndex(
            model_name='allergen',
            index=models.Index(fields=['atc_code'], name='allergen_atc_idx'),
        ),
        migrations.AddIndex(
            model_name='allergen',
            index=models.Index(fields=['category'], name='allergen_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='patientallergy',
            index=models.Index(fields=['patient', 'criticality'], name='pat_allergy_crit_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientallergy',
            constraint=models.UniqueConstraint(fields=('patient', 'allergen'), name='unique_patient_allergen'),
        ),
    ]
