# Generated by Django on 2026-09-17

from django.db import migrations


ESSENTIAL_ALLERGENS = [
    {
        "name": "Pénicillines & Dérivés",
        "category": "medication",
        "atc_code": "J01C",
        "cross_reactivity_group": "Bêta-lactamines",
        "description": "Allergie aux pénicillines majeures. Risque de réaction croisée avec les aminopénicillines et céphalosporines.",
    },
    {
        "name": "Amoxicilline",
        "category": "medication",
        "atc_code": "J01CA04",
        "cross_reactivity_group": "Bêta-lactamines",
        "description": "Aminopénicilline à large spectre (Clamoxyl, Augmentin). Contre-indication absolue en cas d'hypersensibilité immédiate.",
    },
    {
        "name": "Céphalosporines",
        "category": "medication",
        "atc_code": "J01DB",
        "cross_reactivity_group": "Bêta-lactamines",
        "description": "Antibiotiques de la famille des bêta-lactamines (Ceftriaxone, Céfuroxime...). Réactivité croisée possible avec pénicillines.",
    },
    {
        "name": "Sulfamides antibactériens",
        "category": "medication",
        "atc_code": "J01E",
        "cross_reactivity_group": "Sulfamides",
        "description": "Sulfaméthoxazole, Cotrimoxazole (Bactrim). Risque de toxidermies sévères et de syndrome de Lyell.",
    },
    {
        "name": "Aspirine (Acide acétylsalicylique)",
        "category": "medication",
        "atc_code": "N02BA01",
        "cross_reactivity_group": "AINS",
        "description": "Anti-inflammatoire non stéroïdien et antiagrégant plaquettaire. Risque d'asthme induit et de syndrome de Widal.",
    },
    {
        "name": "Ibuprofène & AINS",
        "category": "medication",
        "atc_code": "M01AE01",
        "cross_reactivity_group": "AINS",
        "description": "Anti-inflammatoires non stéroïdiens (Kétoprofène, Diclofénac...). Réactions croisées fréquentes.",
    },
    {
        "name": "Produits de contraste iodés",
        "category": "medication",
        "atc_code": "V08A",
        "cross_reactivity_group": "Produits de contraste",
        "description": "Utilisés en radiologie et scanner. Risque de réactions anaphylactoïdes immédiates.",
    },
    {
        "name": "Latex",
        "category": "biological",
        "atc_code": "",
        "cross_reactivity_group": "Latex",
        "description": "Gants médicaux, sondes, matériel de bloc opératoire. Risque d'allergie croisée avec avocat, banane, kiwi.",
    },
    {
        "name": "Arachides / Cacahuètes",
        "category": "food",
        "atc_code": "",
        "cross_reactivity_group": "Arachides",
        "description": "Allergène alimentaire majeur à fort risque d'anaphylaxie aiguë.",
    },
    {
        "name": "Œufs / Protéines de blanc d'œuf",
        "category": "food",
        "atc_code": "",
        "cross_reactivity_group": "Ovalbumine",
        "description": "Précautions requises lors de l'administration de certains vaccins cultivés sur œuf.",
    },
    {
        "name": "Venin d'hyménoptères (Guêpe / Abeille)",
        "category": "biological",
        "atc_code": "",
        "cross_reactivity_group": "Venins",
        "description": "Risque élevé de choc anaphylactique systémique.",
    },
]


def seed_allergens(apps, schema_editor):
    Allergen = apps.get_model("patients", "Allergen")
    for item in ESSENTIAL_ALLERGENS:
        Allergen.objects.update_or_create(
            name=item["name"],
            defaults={
                "category": item["category"],
                "atc_code": item["atc_code"],
                "cross_reactivity_group": item["cross_reactivity_group"],
                "description": item["description"],
            },
        )


def reverse_seed_allergens(apps, schema_editor):
    Allergen = apps.get_model("patients", "Allergen")
    names = [item["name"] for item in ESSENTIAL_ALLERGENS]
    Allergen.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_allergen_patientallergy_allergen_allergen_name_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_allergens, reverse_seed_allergens),
    ]

