# Generated by Django 6.0.8 on 2026-09-17 09:13

import utils.phone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_seed_essential_allergens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='allergen',
            name='allergen_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='patient_num_idx',
        ),
        migrations.AlterField(
            model_name='allergen',
            name='atc_code',
            field=models.CharField(blank=True, default='', help_text="Code de classification anatomique, thérapeutique et chimique de l'OMS (ex: J01C).", max_length=20, verbose_name='Code ATC'),
        ),
        migrations.AlterField(
            model_name='allergen',
            name='category',
            field=models.CharField(choices=[('medication', 'Médicament / Molécule active'), ('food', 'Alimentaire'), ('environment', 'Environnemental / Aéro-allergène'), ('biological', 'Biologique / Latex / Venin'), ('other', 'Autre substance')], default='medication', max_length=30, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='allergen',
            name='cross_reactivity_group',
            field=models.CharField(blank=True, default='', help_text='Ex: Bêta-lactamines, Sulfamides, AINS.', max_length=100, verbose_name='Groupe de réactivité croisée'),
        ),
        migrations.AlterField(
            model_name='allergen',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nom de la substance'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programmé'), ('waiting', 'En attente'), ('in_consultation', 'En consultation'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('missed', 'Non honoré / Absent')], default='scheduled', max_length=20, verbose_name='Statut du rendez-vous'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_number',
            field=models.CharField(help_text='Numéro unique généré automatiquement au format PAT-YYYY-XXXX.', max_length=32, unique=True, verbose_name='Matricule / Identifiant patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[utils.phone.validate_phone_number], verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='patientallergy',
            name='criticality',
            field=models.CharField(choices=[('low', 'Faible (réaction mineure)'), ('moderate', 'Modérée'), ('high', 'Élevée (Risque vital / Anaphylaxie)'), ('unable_to_assess', 'Indéterminée')], default='high', max_length=25, verbose_name='Niveau de criticité'),
        ),
        migrations.AddIndex(
            model_name='allergen',
            index=models.Index(fields=['cross_reactivity_group'], name='allergen_cross_idx'),
        ),
    ]
