# Generated by Django 6.0.8 on 2026-09-17 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_allergen_allergen_name_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_active',
        ),
        migrations.AddField(
            model_name='patient',
            name='deceased_at',
            field=models.DateTimeField(blank=True, help_text='Renseigné obligatoirement si le patient est déclaré décédé.', null=True, verbose_name='Date et heure du décès'),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('active', 'Actif (Suivi en cours)'), ('archived', 'Archivé (Dossier clos)'), ('deceased', 'Décédé'), ('transferred', 'Transféré (Autre structure)'), ('suspended', 'Suspendu (Identitovigilance / Litige)')], default='active', help_text='Cycle de vie clinique et administratif du dossier patient (aligné FHIR/HL7).', max_length=20, verbose_name='Statut du dossier'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['status'], name='patient_status_idx'),
        ),
    ]
