# Generated by Django 6.0.8 on 2026-09-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_patient_is_active_patient_deceased_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Actif (Suivi en cours)'), ('archived', 'Archivé (Dossier clos)'), ('deceased', 'Décédé'), ('transferred', 'Transféré (Autre structure)'), ('suspended', 'Suspendu (Identitovigilance / Litige)')], default='active', help_text='Cycle de vie clinique et administratif du dossier patient (aligné FHIR/HL7).', max_length=20, verbose_name='Statut du dossier'),
        ),
    ]
