# Generated by Django 6.0.8 on 2026-09-30 18:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_appointment_doctor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, default='', help_text="Saisie déclarative initiale lors de l'admission administrative (Agent d'accueil). Rôle informatif rapide, complété par les allergies codifiées (PatientAllergy) renseignées par le personnel médical pour la sécurisation active des prescriptions.", verbose_name='Allergies connues (déclaration libre)'),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('is_deleted', models.BooleanField(default=False, help_text="Indique si l'enregistrement a été supprimé logiquement.", verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date de suppression')),
                ('consultation_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date et heure de la consultation')),
                ('reason', models.CharField(max_length=255, verbose_name='Motif de la consultation')),
                ('symptoms', models.TextField(blank=True, default='', verbose_name='Symptômes et observations cliniques')),
                ('vital_signs', models.JSONField(blank=True, default=dict, help_text="Ex: {'tension': '12/8', 'poids': 70, 'temperature': 37.2, 'pouls': 75}", verbose_name='Constantes vitales (Tension, Poids, Température, Pouls)')),
                ('diagnosis', models.TextField(blank=True, default='', verbose_name='Diagnostic médical')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes confidentielles / Recommandations')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée')], default='COMPLETED', max_length=20, verbose_name='Statut de la consultation')),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='patients.appointment', verbose_name='Rendez-vous associé')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('doctor', models.ForeignKey(limit_choices_to={'is_personnel_medical': True}, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_consultations', to=settings.AUTH_USER_MODEL, verbose_name='Médecin / Praticien')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient', verbose_name='Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Consultation médicale',
                'verbose_name_plural': 'Consultations médicales',
                'db_table': 'consultations',
                'ordering': ['-consultation_date'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Montant total (FCFA / EUR)')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Montant encaisse')),
                ('status', models.CharField(choices=[('UNPAID', 'Non payée'), ('PARTIALLY_PAID', 'Partiellement payée'), ('PAID', 'Payée'), ('CANCELLED', 'Annulée')], default='UNPAID', max_length=20, verbose_name='Statut de paiement')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='patients.consultation', verbose_name='Consultation associée')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_emises', to=settings.AUTH_USER_MODEL, verbose_name='Caissier / Agent émetteur')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='patients.patient', verbose_name='Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'factures',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('prescribed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de prescription')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Recommandations / Instructions générales')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnances', to='patients.consultation', verbose_name='Consultation associée')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordonnances_delivrees', to=settings.AUTH_USER_MODEL, verbose_name='Médecin prescripteur')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='patients.patient', verbose_name='Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Ordonnance médicale',
                'verbose_name_plural': 'Ordonnances médicales',
                'db_table': 'ordonnances',
                'ordering': ['-prescribed_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneOrdonnance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('medication_name', models.CharField(max_length=200, verbose_name='Nom du médicament / Substance')),
                ('posology', models.CharField(max_length=200, verbose_name='Posologie (ex: 1 cp 3x/jour)')),
                ('duration', models.CharField(max_length=100, verbose_name='Durée du traitement (ex: 7 jours)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité / Boîtes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='patients.ordonnance', verbose_name='Ordonnance')),
            ],
            options={
                'verbose_name': "Ligne d'ordonnance",
                'verbose_name_plural': "Lignes d'ordonnance",
                'db_table': 'lignes_ordonnance',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant régle')),
                ('payment_method', models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte Bancaire'), ('MOBILE_MONEY', 'Mobile Money (Orange/MTN/Moov)'), ('VIREMENT', 'Virement / Chèque')], default='ESPECES', max_length=30, verbose_name='Mode de règlement')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de règlement')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes de caisse')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_encaisses', to=settings.AUTH_USER_MODEL, verbose_name='Caissier')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='patients.facture', verbose_name='Facture associée')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Paiement / Règlement',
                'verbose_name_plural': 'Paiements / Règlements',
                'db_table': 'paiements',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nom de la prestation')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code acte / Tarifaire')),
                ('category', models.CharField(default='CONSULTATION', max_length=50, verbose_name="Catégorie d'acte")),
                ('standard_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarif standard (FCFA / EUR)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Prestation active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Prestation médicale',
                'verbose_name_plural': 'Prestations médicales',
                'db_table': 'prestations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrestationRealisee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total')),
                ('status', models.CharField(choices=[('EN_ATTENTE_CAISSE', 'En attente de facturation'), ('FACTURE', 'Facturé'), ('PAYE', 'Payé')], default='EN_ATTENTE_CAISSE', max_length=25, verbose_name="Statut d'encaissement")),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestations', to='patients.consultation', verbose_name='Consultation associée')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestations_prescrites', to=settings.AUTH_USER_MODEL, verbose_name='Praticien prescripteur / exécutant')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations_realisees', to='patients.patient', verbose_name='Patient')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realisations', to='patients.prestation', verbose_name='Prestation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Prestation réalisée',
                'verbose_name_plural': 'Prestations réalisées',
                'db_table': 'prestations_realisees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['is_deleted', '-created_at'], name='consult_del_created_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['doctor', '-consultation_date'], name='consult_doc_date_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['patient', '-consultation_date'], name='consult_pat_date_idx'),
        ),
    ]
