# Generated by Django 6.0.8 on 2026-09-30 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_seed_default_prestations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de délivrance'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_delivrees', to=settings.AUTH_USER_MODEL, verbose_name='Pharmacien / Agent de délivrance'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente de délivrance'), ('DELIVERED', 'Délivrée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut de délivrance'),
        ),
    ]
