# Generated by Django 6.0.8 on 2026-10-04 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_ordonnance_delivered_at_ordonnance_delivered_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro de reçu'),
        ),
        migrations.AddField(
            model_name='prestationrealisee',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestations_realisees', to='patients.facture', verbose_name='Facture associée'),
        ),
    ]
