# Generated by Django 6.0.8 on 2026-10-04 11:35

import django.db.models.deletion
import django.utils.timezone
import utils.phone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0012_paiement_receipt_number_prestationrealisee_facture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('is_deleted', models.BooleanField(default=False, help_text="Indique si l'enregistrement a été supprimé logiquement.", verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date de suppression')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Catégorie pharmaceutique',
                'verbose_name_plural': 'Catégories pharmaceutiques',
                'db_table': 'pharmacy_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('is_deleted', models.BooleanField(default=False, help_text="Indique si l'enregistrement a été supprimé logiquement.", verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date de suppression')),
                ('name', models.CharField(max_length=200, verbose_name='Dénomination commerciale')),
                ('dci', models.CharField(blank=True, default='', help_text='Dénomination Commune Internationale (ex: Paracétamol, Amoxicilline)', max_length=200, verbose_name='Principe actif / DCI')),
                ('dosage', models.CharField(blank=True, default='', max_length=100, verbose_name='Dosage (ex: 500 mg, 1 g, 250 mg/5 ml)')),
                ('form', models.CharField(blank=True, default='', max_length=100, verbose_name='Forme pharmaceutique (ex: Comprimé, Sirop, Injectable)')),
                ('reference_code', models.CharField(max_length=50, unique=True, verbose_name='Code référence / Code-barres')),
                ('unit', models.CharField(default='Boîte', max_length=50, verbose_name='Unité de conditionnement (ex: Boîte, Flacon, Ampoule)')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix d'achat unitaire standard (FCFA)")),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prix de vente au public (FCFA)')),
                ('min_stock_threshold', models.PositiveIntegerField(default=10, verbose_name="Seuil d'alerte de stock minimum")),
                ('current_stock', models.IntegerField(default=0, verbose_name='Quantité totale en stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='Produit actif')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description / Remarques cliniques')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pharmacy.category', verbose_name='Catégorie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Produit pharmaceutique',
                'verbose_name_plural': 'Produits pharmaceutiques',
                'db_table': 'pharmacy_products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('batch_number', models.CharField(max_length=100, verbose_name='Numéro de lot')),
                ('expiry_date', models.DateField(verbose_name='Date de péremption')),
                ('initial_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantité initiale reçue')),
                ('current_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantité restante en stock')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix d'achat unitaire pour ce lot")),
                ('entry_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'entrée en stock")),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif en stock'), ('DEPLETED', 'Épuisé'), ('EXPIRED', 'Périmé'), ('QUARANTINE', 'En quarantaine / Bloqué')], default='ACTIVE', max_length=20, verbose_name='Statut du lot')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacy.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Lot pharmaceutique',
                'verbose_name_plural': 'Lots pharmaceutiques',
                'db_table': 'pharmacy_batches',
                'ordering': ['expiry_date', 'entry_date'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('sale_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de vente (ex: VTE-2026-0001)')),
                ('client_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Nom du client (si vente anonyme au comptoir)')),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure de la vente')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Sous-total (FCFA)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Remise commerciale (FCFA)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total net à payer (FCFA)')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon / En cours'), ('PENDING_PAYMENT', 'En attente de paiement à la caisse'), ('COMPLETED', 'Payée et finalisée'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=20, verbose_name='Statut de la vente')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes / Instructions de délivrance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('facture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_sale', to='patients.facture', verbose_name='Facture Caisse associée')),
                ('ordonnance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_sales', to='patients.ordonnance', verbose_name='Ordonnance médicale associée')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_sales', to='patients.patient', verbose_name='Patient (si identifié)')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_sales', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur / Pharmacien')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Vente pharmacie',
                'verbose_name_plural': 'Ventes pharmacie',
                'db_table': 'pharmacy_sales',
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité délivrée')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sous-total ligne (FCFA)')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='pharmacy.batch', verbose_name='Lot prélevé (FEFO)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='pharmacy.product', verbose_name='Produit vendu')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.sale', verbose_name='Vente')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Ligne de vente pharmacie',
                'verbose_name_plural': 'Lignes de vente pharmacie',
                'db_table': 'pharmacy_sale_items',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('movement_type', models.CharField(choices=[('IN_PURCHASE', 'Entrée / Réception fournisseur'), ('OUT_SALE', 'Sortie / Vente au comptoir'), ('OUT_DISPENSE', 'Sortie / Délivrance ordonnance'), ('POS_ADJUST', "Ajustement d'inventaire positif"), ('NEG_ADJUST', "Ajustement d'inventaire négatif"), ('EXPIRED', 'Mise au rebut pour péremption'), ('RETURN', 'Retour / Annulation de vente'), ('LOSS', 'Perte ou casse')], max_length=25, verbose_name='Type de mouvement')),
                ('quantity', models.IntegerField(help_text='Positive pour entrée, négative pour sortie', verbose_name='Quantité mouvementée')),
                ('previous_stock', models.IntegerField(verbose_name='Stock avant opération')),
                ('new_stock', models.IntegerField(verbose_name='Stock après opération')),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure du mouvement')),
                ('reference_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Référence opération (ex: N° Vente, N° Réception)')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Motif / Justification du mouvement')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='pharmacy.batch', verbose_name='Lot associé')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='pharmacy.product', verbose_name='Produit concerné')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_movements', to=settings.AUTH_USER_MODEL, verbose_name='Opérateur responsable')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'db_table': 'pharmacy_stock_movements',
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de dernière modification')),
                ('is_deleted', models.BooleanField(default=False, help_text="Indique si l'enregistrement a été supprimé logiquement.", verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date de suppression')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Raison sociale / Nom du fournisseur')),
                ('contact_person', models.CharField(blank=True, default='', max_length=150, verbose_name='Personne de contact')),
                ('telephone', models.CharField(blank=True, default='', max_length=30, validators=[utils.phone.validate_phone_number], verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Adresse email')),
                ('address', models.TextField(blank=True, default='', verbose_name='Adresse géographique')),
                ('is_active', models.BooleanField(default=True, verbose_name='Fournisseur actif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Fournisseur pharmaceutique',
                'verbose_name_plural': 'Fournisseurs pharmaceutiques',
                'db_table': 'pharmacy_suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='pharmacy.supplier', verbose_name='Fournisseur'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='idx_prod_name'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['dci'], name='idx_prod_dci'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['reference_code'], name='idx_prod_ref'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_number'], name='idx_sale_num'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', '-sale_date'], name='idx_sale_status_date'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', '-movement_date'], name='idx_mov_prod_date'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='idx_mov_type'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['product', 'status', 'expiry_date'], name='idx_batch_fefo'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['batch_number'], name='idx_batch_num'),
        ),
    ]
