# Generated by Django 6.0.8 on 2026-10-04 11:53

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pharmacy/products/', validators=[utils.validators.validate_image_file_size], verbose_name='Photo / Image du médicament'),
        ),
    ]
